pipeline:

  validate:
    image: chrisns/packer-ansible
    environment:
    commands:
      - export HOME=/home/packer
      - packer validate packer.json

  inspect:
    image: chrisns/packer-ansible
    environment:
    commands:
      - export HOME=/home/packer
      - packer inspect packer.json

  build:
    image: chrisns/packer-ansible
    environment:
    commands:
      - export HOME=/home/packer
      - packer build packer.json
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    when:
      event: push
      branch: master
